language: node_js

node_js:
- 0.1

branches:
  only:
  - master

before_install:
- npm install hexo-cli -g

install:
- npm install


before_script:
- git config --global user.name 'tbbravo'
- git config --global user.email 'tbbravo@baidu.com'

script:
- hexo g

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
